### ISSUE TITLE
新規登録画面及びログイン画面 テストコーディング

### ISSUE THREAD

**Issue by SENOSuit** [ccino-team/ccino-develop#19]
CcinoのTOP画面からの遷移先である、
・新規登録画面
・ログイン画面
上記の２画面のコーディング

![pc_signin_01](https://cloud.githubusercontent.com/assets/8334098/13277744/8cfe66c4-db0e-11e5-89ec-b31575fb094d.png)

![pc_signup_01](https://cloud.githubusercontent.com/assets/8334098/13277746/92b8e990-db0e-11e5-8203-11af4bba18d7.png)

**Comment by naoyoshikaneko** [comment]
作成完了。Gitにプッシュ済み
